use std::mem::offset_of;

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum RegisterId { // 125 registers in total
    Rax, Rdx, Rcx, Rbx, Rsi, Rdi, Rbp, Rsp,
    R8, R9, R10, R11, R12, R13, R14, R15,
    Rip, Eflags, Cs, Fs, Gs, Ss, Ds, Es, OrigRax,

    Eax, Edx, Ecx, Ebx, Esi, Edi, Ebp, Esp,
    R8d, R9d, R10d, R11d, R12d, R13d, R14d, R15d,

    Ax, Dx, Cx, Bx, Si, Di, Bp, Sp,
    R8w, R9w, R10w, R11w, R12w, R13w, R14w, R15w,

    Ah, Dh, Ch, Bh,
    Al, Dl, Cl, Bl, Sil, Dil, Bpl, Spl,
    R8b, R9b, R10b, R11b, R12b, R13b, R14b, R15b,

    Fcw, Fsw, Ftw, Fop, Frip, Frdp, Mxcsr, Mxcsrmask,

    St0, St1, St2, St3, St4, St5, St6, St7,

    Mm0, Mm1, Mm2, Mm3, Mm4, Mm5, Mm6, Mm7,

    Xmm0, Xmm1, Xmm2, Xmm3, Xmm4, Xmm5, Xmm6, Xmm7,
    Xmm8, Xmm9, Xmm10, Xmm11, Xmm12, Xmm13, Xmm14, Xmm15,

    Dr0, Dr1, Dr2, Dr3, Dr4, Dr5, Dr6, Dr7,
}

#[repr(C)]
struct User {
    /// General purpose registers (GPRs)
    regs: UserRegsStruct,
    /// Validity flag for FPU state (1 if FPU state is valid)
    u_fpvalid: i32,
    /// Padding for 8-byte alignment
    _pad0: [u8; 4],
    /// Floating point unit state (FPU, MMX, SSE registers)
    i387: UserFpRegsStruct,
    /// Text segment size in pages
    u_tsize: u64,
    /// Data segment size in pages
    u_dsize: u64,
    /// Stack segment size in pages
    u_ssize: u64,
    /// Starting virtual address of text segment
    start_code: u64,
    /// Starting virtual address of stack
    start_stack: u64,
    /// Signal that caused core dump (or 0)
    signal: i64,
    /// Reserved/padding
    _pad1: [u8; 8],
    /// Pointer to register state (used by gdb)
    u_ar0: *mut UserRegsStruct,
    /// Pointer to FPU state
    u_fpstate: *mut UserFpRegsStruct,
    /// Magic number identifying core file format
    magic: u64,
    /// Command name (process name, null-terminated)
    u_comm: [u8; 32],
    /// Hardware debug registers (dr0-dr7)
    u_debugreg: [u64; 8],
    /// CPU exception error code
    error_code: u64,
    /// Fault address that caused exception
    fault_address: u64,
}

#[repr(C)]
struct UserRegsStruct {
    r15: u64,
    r14: u64,
    r13: u64,
    r12: u64,
    rbp: u64,
    rbx: u64,
    r11: u64,
    r10: u64,
    r9: u64,
    r8: u64,
    rax: u64,
    rcx: u64,
    rdx: u64,
    rsi: u64,
    rdi: u64,
    /// Original value of rax before system call (used by ptrace for syscall tracking)
    orig_rax: u64,
    /// Instruction pointer
    rip: u64,
    /// Code segment selector
    cs: u64,
    /// Flags register
    eflags: u64,
    /// Stack pointer
    rsp: u64,
    /// Stack segment selector
    ss: u64,
    fs_base: u64,
    gs_base: u64,
    ds: u64,
    es: u64,
    fs: u64,
    gs: u64,
}

#[repr(C)]
struct UserFpRegsStruct {
    cwd: u16,           // Control word
    swd: u16,           // Status word
    ftw: u16,           // Tag word
    fop: u16,           // Last instruction opcode
    rip: u64,           // Instruction pointer
    rdp: u64,           // Data pointer
    mxcsr: u32,         // MXCSR register
    mxcr_mask: u32,     // MXCSR mask
    /// x87 FPU / MMX registers (8 registers × 16 bytes each = 128 bytes)
    ///
    /// Each x87 register (ST0-ST7) is 80 bits (10 bytes) but stored in 16 bytes.
    /// MMX registers (MM0-MM7) alias the low 64 bits of ST0-ST7.
    /// Note: [u32; 32] = 32 × 4 = 128 bytes
    st_space: [u32; 32],
    // 8 FP registers, 16 bytes each (128 bytes total)
    /// SSE registers (16 XMM registers × 16 bytes each = 256 bytes)
    /// Note: [u32; 64] = 64 × 4 = 256 bytes
    xmm_space: [u32; 64],  // 16 XMM registers, 16 bytes each (256 bytes total)
    padding: [u32; 24],
}

const fn gpr_offset(reg_offset: usize) -> usize{
    offset_of!(User, regs) + reg_offset
}

const fn fpr_offset(reg_offset: usize) -> usize {
    offset_of!(User, i387) + reg_offset
}

const fn dr_offset(number: usize) -> usize {
    offset_of!(User, u_debugreg) + number * 8
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum RegisterType {
    Gpr,
    SubGpr,
    Fpr,
    Dr
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum RegisterFormat {
    Uint,
    DoubleFloat,
    LongDouble,
    Vector
}

pub struct Register {
    id: RegisterId,
    name: &'static str,
    size: usize,
    offset: usize,
    register_type: RegisterType,
    register_format: RegisterFormat,
    dwarf_id: i32
}

impl Register {
    pub fn by_name(name: &str) -> Option<&'static Self> {
        REGISTERS.iter().find(|r| r.name == name)
    }
    pub fn by_dwarf_id(dwarf_id: i32) -> Option<&'static Self> {
        REGISTERS.iter().find(|r| r.dwarf_id == dwarf_id)
    }
    pub fn by_id(id: RegisterId) -> &'static Self {
        &REGISTERS[id as usize]
    }
}

pub const REGISTERS: &[Register] = &[
    // ========== 64-bit GPRs ==========
    Register {
        id: RegisterId::Rax,
        name: "rax",
        dwarf_id: 0,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rax)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Rdx,
        name: "rdx",
        dwarf_id: 1,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdx)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Rcx,
        name: "rcx",
        dwarf_id: 2,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rcx)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Rbx,
        name: "rbx",
        dwarf_id: 3,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbx)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Rsi,
        name: "rsi",
        dwarf_id: 4,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rsi)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Rdi,
        name: "rdi",
        dwarf_id: 5,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdi)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Rbp,
        name: "rbp",
        dwarf_id: 6,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbp)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Rsp,
        name: "rsp",
        dwarf_id: 7,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rsp)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R8,
        name: "r8",
        dwarf_id: 8,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, r8)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R9,
        name: "r9",
        dwarf_id: 9,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, r9)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R10,
        name: "r10",
        dwarf_id: 10,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, r10)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R11,
        name: "r11",
        dwarf_id: 11,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, r11)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R12,
        name: "r12",
        dwarf_id: 12,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, r12)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R13,
        name: "r13",
        dwarf_id: 13,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, r13)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R14,
        name: "r14",
        dwarf_id: 14,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, r14)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R15,
        name: "r15",
        dwarf_id: 15,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, r15)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Rip,
        name: "rip",
        dwarf_id: 16,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, rip)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Eflags,
        name: "eflags",
        dwarf_id: 49,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, eflags)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Cs,
        name: "cs",
        dwarf_id: 51,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, cs)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Fs,
        name: "fs",
        dwarf_id: 54,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, fs)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Gs,
        name: "gs",
        dwarf_id: 55,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, gs)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Ss,
        name: "ss",
        dwarf_id: 52,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, ss)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Ds,
        name: "ds",
        dwarf_id: 53,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, ds)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Es,
        name: "es",
        dwarf_id: 50,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, es)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::OrigRax,
        name: "orig_rax",
        dwarf_id: -1,
        size: 8,
        offset: gpr_offset(offset_of!(UserRegsStruct, orig_rax)),
        register_type: RegisterType::Gpr,
        register_format: RegisterFormat::Uint,
    },

    // ========== 32-bit subregisters ==========
    Register {
        id: RegisterId::Eax,
        name: "eax",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, rax)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Edx,
        name: "edx",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Ecx,
        name: "ecx",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, rcx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Ebx,
        name: "ebx",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Esi,
        name: "esi",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, rsi)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Edi,
        name: "edi",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdi)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Ebp,
        name: "ebp",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbp)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Esp,
        name: "esp",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, rsp)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R8d,
        name: "r8d",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, r8)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R9d,
        name: "r9d",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, r9)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R10d,
        name: "r10d",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, r10)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R11d,
        name: "r11d",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, r11)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R12d,
        name: "r12d",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, r12)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R13d,
        name: "r13d",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, r13)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R14d,
        name: "r14d",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, r14)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R15d,
        name: "r15d",
        dwarf_id: -1,
        size: 4,
        offset: gpr_offset(offset_of!(UserRegsStruct, r15)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },

    // ========== 16-bit subregisters ==========
    Register {
        id: RegisterId::Ax,
        name: "ax",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, rax)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dx,
        name: "dx",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Cx,
        name: "cx",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, rcx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Bx,
        name: "bx",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Si,
        name: "si",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, rsi)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Di,
        name: "di",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdi)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Bp,
        name: "bp",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbp)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Sp,
        name: "sp",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, rsp)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R8w,
        name: "r8w",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, r8)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R9w,
        name: "r9w",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, r9)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R10w,
        name: "r10w",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, r10)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R11w,
        name: "r11w",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, r11)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R12w,
        name: "r12w",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, r12)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R13w,
        name: "r13w",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, r13)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R14w,
        name: "r14w",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, r14)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R15w,
        name: "r15w",
        dwarf_id: -1,
        size: 2,
        offset: gpr_offset(offset_of!(UserRegsStruct, r15)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },

    // ========== 8-bit high subregisters ==========
    Register {
        id: RegisterId::Ah,
        name: "ah",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rax)) + 1,
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dh,
        name: "dh",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdx)) + 1,
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Ch,
        name: "ch",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rcx)) + 1,
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Bh,
        name: "bh",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbx)) + 1,
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },

    // ========== 8-bit low subregisters ==========
    Register {
        id: RegisterId::Al,
        name: "al",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rax)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dl,
        name: "dl",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Cl,
        name: "cl",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rcx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Bl,
        name: "bl",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbx)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Sil,
        name: "sil",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rsi)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dil,
        name: "dil",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rdi)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Bpl,
        name: "bpl",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rbp)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Spl,
        name: "spl",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, rsp)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R8b,
        name: "r8b",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, r8)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R9b,
        name: "r9b",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, r9)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R10b,
        name: "r10b",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, r10)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R11b,
        name: "r11b",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, r11)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R12b,
        name: "r12b",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, r12)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R13b,
        name: "r13b",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, r13)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R14b,
        name: "r14b",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, r14)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::R15b,
        name: "r15b",
        dwarf_id: -1,
        size: 1,
        offset: gpr_offset(offset_of!(UserRegsStruct, r15)),
        register_type: RegisterType::SubGpr,
        register_format: RegisterFormat::Uint,
    },

    // ========== Floating Point Control Registers ==========
    Register {
        id: RegisterId::Fcw,
        name: "fcw",
        dwarf_id: 65,
        size: std::mem::size_of::<u16>(),
        offset: fpr_offset(offset_of!(UserFpRegsStruct, cwd)),
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Fsw,
        name: "fsw",
        dwarf_id: 66,
        size: std::mem::size_of::<u16>(),
        offset: fpr_offset(offset_of!(UserFpRegsStruct, swd)),
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Ftw,
        name: "ftw",
        dwarf_id: -1,
        size: std::mem::size_of::<u16>(),
        offset: fpr_offset(offset_of!(UserFpRegsStruct, ftw)),
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Fop,
        name: "fop",
        dwarf_id: -1,
        size: std::mem::size_of::<u16>(),
        offset: fpr_offset(offset_of!(UserFpRegsStruct, fop)),
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Frip,
        name: "frip",
        dwarf_id: -1,
        size: std::mem::size_of::<u64>(),
        offset: fpr_offset(offset_of!(UserFpRegsStruct, rip)),
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Frdp,
        name: "frdp",
        dwarf_id: -1,
        size: std::mem::size_of::<u64>(),
        offset: fpr_offset(offset_of!(UserFpRegsStruct, rdp)),
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Mxcsr,
        name: "mxcsr",
        dwarf_id: 64,
        size: std::mem::size_of::<u32>(),
        offset: fpr_offset(offset_of!(UserFpRegsStruct, mxcsr)),
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Mxcsrmask,
        name: "mxcsrmask",
        dwarf_id: -1,
        size: std::mem::size_of::<u32>(),
        offset: fpr_offset(offset_of!(UserFpRegsStruct, mxcr_mask)),
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Uint,
    },

    // ========== ST (FPU Stack) Registers ==========
    // ST registers are 10 bytes in hardware but stored as 16 bytes
    Register {
        id: RegisterId::St0,
        name: "st0",
        dwarf_id: 33,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 0 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::LongDouble,
    },
    Register {
        id: RegisterId::St1,
        name: "st1",
        dwarf_id: 34,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 1 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::LongDouble,
    },
    Register {
        id: RegisterId::St2,
        name: "st2",
        dwarf_id: 35,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 2 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::LongDouble,
    },
    Register {
        id: RegisterId::St3,
        name: "st3",
        dwarf_id: 36,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 3 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::LongDouble,
    },
    Register {
        id: RegisterId::St4,
        name: "st4",
        dwarf_id: 37,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 4 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::LongDouble,
    },
    Register {
        id: RegisterId::St5,
        name: "st5",
        dwarf_id: 38,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 5 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::LongDouble,
    },
    Register {
        id: RegisterId::St6,
        name: "st6",
        dwarf_id: 39,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 6 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::LongDouble,
    },
    Register {
        id: RegisterId::St7,
        name: "st7",
        dwarf_id: 40,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 7 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::LongDouble,
    },

    // ========== MM (MMX) Registers ==========
    // MM registers are 8 bytes but stored with 16-byte alignment
    Register {
        id: RegisterId::Mm0,
        name: "mm0",
        dwarf_id: 41,
        size: 8,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 0 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Mm1,
        name: "mm1",
        dwarf_id: 42,
        size: 8,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 1 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Mm2,
        name: "mm2",
        dwarf_id: 43,
        size: 8,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 2 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Mm3,
        name: "mm3",
        dwarf_id: 44,
        size: 8,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 3 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Mm4,
        name: "mm4",
        dwarf_id: 45,
        size: 8,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 4 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Mm5,
        name: "mm5",
        dwarf_id: 46,
        size: 8,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 5 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Mm6,
        name: "mm6",
        dwarf_id: 47,
        size: 8,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 6 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Mm7,
        name: "mm7",
        dwarf_id: 48,
        size: 8,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, st_space)) + 7 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },

    // ========== XMM (SSE) Registers ==========
    Register {
        id: RegisterId::Xmm0,
        name: "xmm0",
        dwarf_id: 17,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 0 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm1,
        name: "xmm1",
        dwarf_id: 18,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 1 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm2,
        name: "xmm2",
        dwarf_id: 19,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 2 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm3,
        name: "xmm3",
        dwarf_id: 20,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 3 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm4,
        name: "xmm4",
        dwarf_id: 21,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 4 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm5,
        name: "xmm5",
        dwarf_id: 22,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 5 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm6,
        name: "xmm6",
        dwarf_id: 23,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 6 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm7,
        name: "xmm7",
        dwarf_id: 24,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 7 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm8,
        name: "xmm8",
        dwarf_id: 25,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 8 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm9,
        name: "xmm9",
        dwarf_id: 26,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 9 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm10,
        name: "xmm10",
        dwarf_id: 27,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 10 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm11,
        name: "xmm11",
        dwarf_id: 28,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 11 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm12,
        name: "xmm12",
        dwarf_id: 29,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 12 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm13,
        name: "xmm13",
        dwarf_id: 30,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 13 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm14,
        name: "xmm14",
        dwarf_id: 31,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 14 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },
    Register {
        id: RegisterId::Xmm15,
        name: "xmm15",
        dwarf_id: 32,
        size: 16,
        offset: fpr_offset(offset_of!(UserFpRegsStruct, xmm_space)) + 15 * 16,
        register_type: RegisterType::Fpr,
        register_format: RegisterFormat::Vector,
    },

    // ========== Debug Registers ==========
    Register {
        id: RegisterId::Dr0,
        name: "dr0",
        dwarf_id: -1,
        size: 8,
        offset: dr_offset(0),
        register_type: RegisterType::Dr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dr1,
        name: "dr1",
        dwarf_id: -1,
        size: 8,
        offset: dr_offset(1),
        register_type: RegisterType::Dr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dr2,
        name: "dr2",
        dwarf_id: -1,
        size: 8,
        offset: dr_offset(2),
        register_type: RegisterType::Dr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dr3,
        name: "dr3",
        dwarf_id: -1,
        size: 8,
        offset: dr_offset(3),
        register_type: RegisterType::Dr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dr4,
        name: "dr4",
        dwarf_id: -1,
        size: 8,
        offset: dr_offset(4),
        register_type: RegisterType::Dr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dr5,
        name: "dr5",
        dwarf_id: -1,
        size: 8,
        offset: dr_offset(5),
        register_type: RegisterType::Dr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dr6,
        name: "dr6",
        dwarf_id: -1,
        size: 8,
        offset: dr_offset(6),
        register_type: RegisterType::Dr,
        register_format: RegisterFormat::Uint,
    },
    Register {
        id: RegisterId::Dr7,
        name: "dr7",
        dwarf_id: -1,
        size: 8,
        offset: dr_offset(7),
        register_type: RegisterType::Dr,
        register_format: RegisterFormat::Uint,
    },
];